version: "1.0.{build}"

environment:
  global:
    DEPLOY_USER_NAME: 'ctags-win32 CI'
    DEPLOY_USER_EMAIL: 'ctags-win32-ci@users.noreply.github.com'
    CI_KEY:
      secure: lDGFwcq2G99xSBX+CQPzJdZyYI4YJ5mwx7sZiHckT46u51oTfMuYxHVQnPSoPrDV

  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
    - compiler: msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32

matrix:
  fast_finish: true

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor.bat build'

after_build:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor.bat package'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor.bat test'


artifacts:
  - path: ctags\ctags-*.zip


before_deploy:
  - for /f "delims=" %%i in (%APPVEYOR_BUILD_FOLDER%\gitlog.txt) do set GITLOG=%%i

deploy:
  - provider: GitHub
    description: |
      Universal Ctags Win32 daily builds ([more information](https://ctags.io)).

      ### Changes:

      $(GITLOG)

    auth_token:
      secure: WqjLi6FMpAWGSZvDSpVaZ3hNhE69MVeqGNh0CwMcXtu/pPKiLbX+KmBbActqt8Di
    artifact: /ctags/
    prerelease: true
    on:
      appveyor_repo_tag: true

# vim: ts=2 sw=2 et
